<?php

namespace App\Http\Livewire\Report\IfView\Daaia001;

use App\Models\Catalogue\aModel;
use App\Models\Catalogue\Municipal;
use App\Models\Catalogue\Nacionality;
use App\Models\Catalogue\State;
use App\Models\Report\Daaia001;
use Livewire\Component;
use Livewire\WithFileUploads;

class Create extends Component
{
    public $idReporter,$id_reporter,$state_id,$municipal_id,$daaia001,$nacionalities_id,$nationalitycopilot_id;
    public $exactPlace,$city,$latitude,$longitude,$date,$time,$aeronauticalAuthority,$flight_phase,$indicate,$collision,
    $altitudeEvent,$maker,$modelReport,$serialNumber,$enrollment,$amateur,$maximumWeight,$accidentWeight,$nose,$datum,
    $noseI,$datumI,$aircraftCategory,$indicateI,$airworthiness,$indicateII,$numberSeats,$flightCrew,$cabinCrew,$passengerSeats,
    $undercarriage,$MaintenanceProgram,$specify,$lastInspection,$other,$lastInspectionDate,$gliderHours,$hoursLastInsp,$hoursTimeAccident,
    $ifrTeam,$collapseSystem,$fireSystem,$type,$eltInstalled,$eltActivated,$eltManufacturer,$eltModel,$eltSerial,$eltBattery,$engineType,
    $reciprocatingSystem,$makerPropeller,$modelPropeller,$pitchPropeller,$manufacturerEngine,$modelEngine,$powerEngine,$engineSerie1,
    $manufacturingDate1,$totalTime1,$lastIspection1,$lastRrepair1,$engineSerie2,$manufacturingDate2,$totalTime2,$lastIspection2,$lastRrepair2,
    $engineSerie3,$manufacturingDate3,$totalTime3,$lastIspection3,$lastRrepair3,$engineSerie4,$manufacturingDate4,$totalTime4,$lastIspection4,
    $lastRrepair4,$nameOwner1,$directionOwner1,$nameOperator1,$directionOperator1,$flightPurpose,$operation,$loadOperation,
    $passengersHow,$concessionType,$others,$tuitionInvolved,$makerInvolved,$modelInvolved,$damageInvolved,$nameOwner2,$directionOwner2,
    $nameOperator2,$directionOperator2,$malfunction,$a_model_id,$descriptionFail,$componentHours,$componentCycles,$componentInspection,$presenceFire,
    $explosion,$describeDamage,$identificationOACI,$nameAerodrome,$distanceAerodrome,$directionAerodrome,$elevation,$proximityAirport,$approachSegment,
    $approachIFR,$approachVFR,$trackHeader,$longitude2,$broad,$materialHead,$conditionsRunway,$lastTakeoff,$timeTakeoff,$destinationAirport,$planFlight,
    $clearanceFlight,$eventOccurred,$loadAircraft,$otherAircraft,$litersFuel,$gallonsfuel,$typeFuel,$specifyFuel,$otherService,$evacuationAircraft,$evacuationDescription,
    $installationObservation,$timeObservation,$distanceAccident,$directionAccident,$sourceInformation,$obtainedInformation,$lightConditions,$skyClouds,$ceiling,
    $lowestCloud,$visibilityRestriction,$Wind,$orientation,$intensity,$typeTurbulence,$severityTurbulence,$weatherConditions,$currentTimeaccident,$temperature,$altimeter,
    $altitudeDensity,$DewPoint,$precipitationType,$nameCommander,$datebirthCommander,$domicileCommander,$classLicense,$numberLicense,$validityLicense,
    $pilotAircraft ,$pilotBumpy,$pilotMultiengine,$pilotInstruments,$instructorAircraft,$instructorRugged ,$instructorMultiengine ,$instructorInstruments,$copilotAircraft,
    $copilotRugged,$copilotMultiengine ,$copilotInstruments,$daysAircraft90,$daysRugged90,$daysMultiengine90,$daysInstruments90,$daysAircraft30,$daysRugged30,$daysMultiengine30,
    $daysInstruments30,$hoursAircraft24,$hoursRugged24,$hoursMultiengine24,$hoursInstruments24,$capabilities,$medicalCertificate,$limitationsCertificate,$exceptionCertificate,
    $observationsCertificate,$otherCertificate,$occupiedSeat,$injury,$performsFunctions,$seatBelt,$theHarness,$inspectionDate,$verificationDate,$nameCopilot,$datebirthCopilot,
    $domicileCopilot,$classLicense2,$numberLicense2,$validityLicense2;
        



    public $copyRevalidation,$filesPermissions,$filesLatestservices,$filereceiptFuel,$fileProcedures,$fileForecast,$fileLicense;
    public $states,$municipals,$models,$nacionality;
    
    use WithFileUploads;
    public function rules()
    {
        return [
            'exactPlace' => 'required',
            'state_id' => 'required',
            'municipal_id' => 'required',
            'city' => 'required',
            'latitude' => 'required',
            'longitude' => 'required',
            'date' => 'required',
            'time' => 'required',
            'aeronauticalAuthority' => 'required',
            'flight_phase' => 'required',
            'indicate' => 'required',
            'collision' => 'required',
            'altitudeEvent' => 'required',
            'maker' => 'required',
            'modelReport' => 'required',
            'serialNumber' => 'required',
            'enrollment' => 'required',
            'amateur' => 'required',
            'maximumWeight' => 'required',
            'accidentWeight' => 'required',
            'nose' => 'required',
            'datum' => 'required',
            'noseI' => 'required',
            'datumI' => 'required',
            'aircraftCategory' => 'required',
            'indicateI' => 'required',
            'airworthiness' => 'required',
            'indicateII' => 'required',
            'numberSeats' => 'required',
            'flightCrew' => 'required',
            'cabinCrew' => 'required',
            'passengerSeats' => 'required',
            'undercarriage' => 'required',
            'MaintenanceProgram' => 'required',
            'specify' => 'required',
            'lastInspection' => 'required',
            'other' => 'required',
            'lastInspectionDate' => 'required',
            'gliderHours' => 'required',
            'hoursLastInsp' => 'required',
            'hoursTimeAccident' => 'required',
            'ifrTeam' => 'required',            
            'collapseSystem' => 'required',
            'fireSystem' => 'required',
            'type' => 'required',
            'eltInstalled' => 'required',
            'eltActivated' => 'required',
            'eltManufacturer' => 'required',
            'eltModel' => 'required',
            'eltSerial' => 'required',
            'eltBattery' => 'required',
            'engineType' => 'required',
            'reciprocatingSystem' => 'required',
            'makerPropeller' => 'required',
            'modelPropeller' => 'required',
            'pitchPropeller' => 'required',
            'manufacturerEngine' => 'required',
            'modelEngine' => 'required',
            'powerEngine' => 'required',
            // 'copyRevalidation'=> 'required|mimetypes:application/pdf|max:500',            
            'nameOwner1' => 'required',
            'directionOwner1' => 'required',
            'nameOperator1' => 'required',
            'directionOperator1' => 'required',
            'flightPurpose' => 'required',
            'operation' => 'required',
            'loadOperation' => 'required',
            'passengersHow' => 'required',
            'concessionType' => 'required',
            'others' => 'required',
            // 'filesPermissions'=> 'required|mimetypes:application/pdf|max:500',            
            'tuitionInvolved' => 'required',
            'makerInvolved' => 'required',
            'modelInvolved' => 'required',
            'damageInvolved' => 'required',
            'nameOwner2' => 'required',
            'directionOwner2' => 'required',
            'nameOperator2' => 'required',
            'directionOperator2' => 'required',
            'malfunction' => 'required',
            'descriptionFail' => 'required',
            'componentHours' => 'required',
            'componentCycles' => 'required',
            'componentInspection' => 'required',
            // 'filesLatestservices'=> 'required|mimetypes:application/pdf|max:500',
            'a_model_id' => 'required',
            'presenceFire' => 'required',
            'explosion' => 'required',
            'describeDamage' => 'required',
            'identificationOACI' => 'required',
            'nameAerodrome' => 'required',
            'distanceAerodrome' => 'required',
            'directionAerodrome' => 'required',
            'elevation' => 'required',
            'proximityAirport'=>'required',
            'approachSegment'=>'required',
            'approachIFR'=>'required',
            'approachVFR'=>'required',
            'trackHeader'=>'required',
            'longitude2'=>'required',
            'broad'=>'required',
            'materialHead'=>'required',
            'conditionsRunway'=>'required',
            'lastTakeoff' => 'required',
            'timeTakeoff' => 'required',
            'destinationAirport' => 'required',
            'planFlight' => 'required',
            'clearanceFlight' => 'required',
            'eventOccurred' => 'required',
            'loadAircraft' => 'required',
            'otherAircraft' => 'required',
            'litersFuel' => 'required',
            'gallonsfuel' => 'required',
            'typeFuel' => 'required',
            'specifyFuel' => 'required',
            'otherService' => 'required',
            // 'filereceiptFuel'=> 'required|mimetypes:application/pdf|max:500',
            'evacuationAircraft' => 'required',
            'evacuationDescription' => 'required',
            // 'fileProcedures'=> 'required|mimetypes:application/pdf|max:500',
            'installationObservation' => 'required',
            'timeObservation' => 'required',
            'distanceAccident' => 'required',
            'directionAccident' => 'required',
            'sourceInformation' => 'required',
            'obtainedInformation' => 'required',
            'lightConditions' => 'required',
            'skyClouds' => 'required',
            'ceiling' => 'required',
            'lowestCloud' => 'required',
            'visibilityRestriction' => 'required',
            'Wind' => 'required',
            'orientation' => 'required',
            'intensity' => 'required',
            'typeTurbulence' => 'required',
            'severityTurbulence' => 'required',
            'weatherConditions' => 'required',
            'currentTimeaccident' => 'required',
            'temperature' => 'required',
            'altimeter' => 'required',
            'altitudeDensity' => 'required',
            'DewPoint' => 'required',
            'precipitationType' => 'required',
            // 'fileForecast'=> 'required|mimetypes:application/pdf|max:500',
            'nameCommander' => 'required',
            'nacionalities_id' => 'required',
            'datebirthCommander' => 'required',
            'domicileCommander' => 'required',
            'classLicense' => 'required',
            'numberLicense' => 'required',
            'validityLicense' => 'required',
            'pilotAircraft ' => 'required',
            'pilotBumpy' => 'required',
            'pilotMultiengine' => 'required',
            'pilotInstruments' => 'required',
            'instructorAircraft' => 'required',
            'instructorRugged ' => 'required',
            'instructorMultiengine ' => 'required',
            'instructorInstruments' => 'required',
            'copilotAircraft' => 'required',
            'copilotRugged' => 'required',
            'copilotMultiengine ' => 'required',
            'copilotInstruments' => 'required',
            'daysAircraft90' => 'required',
            'daysRugged90' => 'required',
            'daysMultiengine90' => 'required',
            'daysInstruments90' => 'required',
            'daysAircraft30' => 'required',
            'daysRugged30' => 'required',
            'daysMultiengine30' => 'required',
            'daysInstruments30' => 'required',
            'hoursAircraft24' => 'required',
            'hoursRugged24' => 'required',
            'hoursMultiengine24' => 'required',
            'hoursInstruments24' => 'required',

            'capabilities' => 'required',
            'medicalCertificate' => 'required',
            'limitationsCertificate' => 'required',
            'exceptionCertificate' => 'required',
            'observationsCertificate' => 'required',
            'otherCertificate' => 'required',
            'occupiedSeat' => 'required',
            'injury' => 'required',
            'performsFunctions' => 'required',
            'seatBelt' => 'required',
            'theHarness' => 'required',
            'inspectionDate' => 'required',
            'verificationDate' => 'required',
            // 'fileLicense'=> 'required|mimetypes:application/pdf|max:500',                        
            'nameCopilot' => 'required',
            'nationalitycopilot_id' => 'required',
            'datebirthCopilot' => 'required',
            'domicileCopilot' => 'required',
            'classLicense2' => 'required',
            'numberLicense2' => 'required',
            'validityLicense2' => 'required',
            


        ];
    }

    public function mount($idReporter){
    $this->idReporter = $idReporter;
    $this->states = State::all();
    $this->municipals = collect();
    $this->models = aModel::all();
    $this->nacionality = Nacionality::all();
    }
    public function render()
    {
        return view('livewire.report.if-view.daaia001.create')
            ->extends('layouts.app')
            ->section('content');
    }
    public function updatedcopyRevalidation()
    {
        $this->validate(['copyRevalidation' => 'mimetypes:application/pdf|max:5000']);
    }
    public function  updatedfilesPermissions(){
        $this->validate(['filesPermissions' => 'mimetypes:application/pdf|max:5000']);        
    }
    public function updatedfilesLatestservices(){
        $this->validate(['filesLatestservices' => 'mimetypes:application/pdf|max:5000']);                
    }
    public function updatedfilereceiptFuel(){
        $this->validate(['filereceiptFuel' => 'mimetypes:application/pdf|max:5000']);                                
    }
    public function updatedfileProcedures(){
        $this->validate(['fileProcedures' => 'mimetypes:application/pdf|max:5000']);                                        
    } 
    public function updatedfileForecast(){
        $this->validate(['fileForecast' => 'mimetypes:application/pdf|max:5000']);                                        
    }     
    public function updatedfileLicense(){
        $this->validate(['fileLicense' => 'mimetypes:application/pdf|max:5000']);                                        
    }     

    public function updatedStateId($state_id){
        $this->municipals = Municipal::where('state_id',$state_id)->get();
    }

    public function save(){
        // $this->validate();
        // dd($this->directionOwner);
        $this->daaia001 = Daaia001::updateOrCreate(
            ['id' => $this->id_reporter],
            [
                'general_user_id' => $this->idReporter,
                'exactPlace' => $this->exactPlace,
                'state_id' => $this->state_id,
                'municipal_id' => $this->municipal_id,
                'city' => $this->city,
                'latitude' => $this->latitude,
                'longitude' => $this->longitude,
                'date' => $this->date,
                'time' => $this->time,
                'aeronauticalAuthority' => $this->aeronauticalAuthority,
                'flight_phase' => $this->flight_phase,
                'indicate' => $this->indicate,
                'collision' => $this->collision,
                'altitudeEvent' => $this->altitudeEvent,
                'maker' => $this->maker,
                'modelReport' => $this->modelReport,
                'serialNumber' => $this->serialNumber,
                'enrollment' => $this->enrollment,
                'amateur' => $this->amateur,
                'maximumWeight' => $this->maximumWeight,
                'accidentWeight' => $this->accidentWeight,
                'nose' => $this->nose,
                'datum' => $this->datum,
                'noseI' => $this->noseI,
                'datumI' => $this->datumI,
                'aircraftCategory' => $this->aircraftCategory,
                'indicateI' => $this->indicateI,
                'airworthiness' => $this->airworthiness,
                'indicateII' => $this->indicateII,
                'numberSeats' => $this->numberSeats,
                'flightCrew' => $this->flightCrew,
                'cabinCrew' => $this->cabinCrew,
                'passengerSeats' => $this->passengerSeats,
                'undercarriage' => $this->undercarriage,
                'MaintenanceProgram' => $this->MaintenanceProgram,
                'specify' => $this->specify,
                'lastInspection' => $this->lastInspection,
                'other' => $this->other,
                'lastInspectionDate' => $this->lastInspectionDate,
                'gliderHours' => $this->gliderHours,
                'hoursLastInsp' => $this->hoursLastInsp,
                'hoursTimeAccident' => $this->hoursTimeAccident,
                'ifrTeam' => $this->ifrTeam,
                'collapseSystem' => $this->collapseSystem,
                'fireSystem' => $this->fireSystem,
                'type' => $this->type,
                'eltInstalled' => $this->eltInstalled,
                'eltActivated' => $this->eltActivated,
                'eltManufacturer' => $this->eltManufacturer,
                'eltModel' => $this->eltModel,
                'eltSerial' => $this->eltSerial,
                'eltBattery' => $this->eltBattery,
                'engineType' => $this->engineType,
                'reciprocatingSystem' => $this->reciprocatingSystem,
                'makerPropeller' => $this->makerPropeller,
                'modelPropeller' => $this->modelPropeller,
                'pitchPropeller' => $this->pitchPropeller,
                'manufacturerEngine' => $this->manufacturerEngine,
                'modelEngine' => $this->modelEngine,
                'powerEngine' => $this->powerEngine,
                'engineSerie1' => $this->engineSerie1,
                'manufacturingDate1' => $this->manufacturingDate1,
                'totalTime1' => $this->totalTime1,
                'lastIspection1' => $this->lastIspection1,
                'lastRrepair1' => $this->lastRrepair1,
                'engineSerie2' => $this->engineSerie2,
                'manufacturingDate2' => $this->manufacturingDate2,
                'totalTime2' => $this->totalTime2,
                'lastIspection2' => $this->lastIspection2,
                'lastRrepair2' => $this->lastRrepair2,
                'engineSerie3' => $this->engineSerie3,
                'manufacturingDate3' => $this->manufacturingDate3,
                'totalTime3' => $this->totalTime3,
                'lastIspection3' => $this->lastIspection3,
                'lastRrepair3' => $this->lastRrepair3,
                'engineSerie4' => $this->engineSerie4,
                'manufacturingDate4' => $this->manufacturingDate4,
                'totalTime4' => $this->totalTime4,
                'lastIspection4' => $this->lastIspection4,
                'lastRrepair4' => $this->lastRrepair4,
                // 'copyRevalidation' => $this->copyRevalidation->store('documentos', 'public','Revalidacion'),
                'nameOwner1' => $this->nameOwner1,
                'directionOwner1' => $this->directionOwner1,
                'nameOperator1' => $this->nameOperator1,
                'directionOperator1' => $this->directionOperator1,
                'flightPurpose' => $this->flightPurpose,
                'operation' => $this->operation,
                'loadOperation' => $this->loadOperation,
                'passengersHow' => $this->passengersHow,
                'concessionType' => $this->concessionType,
                'others' => $this->others,
                // 'filesPermissions' => $this->filesPermissions->store('documentos', 'public','Permisos'),
                'tuitionInvolved' => $this->tuitionInvolved,
                'makerInvolved' => $this->makerInvolved,
                'modelInvolved' => $this->modelInvolved,
                'damageInvolved' => $this->damageInvolved,
                'nameOwner2' => $this->nameOwner2,
                'directionOwner2' => $this->directionOwner2,
                'nameOperator2' => $this->nameOperator2,
                'directionOperator2' => $this->directionOperator2,
                'malfunction' => $this->malfunction,
                'descriptionFail' => $this->descriptionFail,
                'componentHours' => $this->componentHours,
                'componentCycles' => $this->componentCycles,
                'componentInspection' => $this->lastInspection,
                // 'filesLatestservices' => $this->filesLatestservices->store('documentos', 'public','Servicios'),                
                'a_model_id' => $this->a_model_id,
                'presenceFire' => $this->presenceFire,
                'explosion' => $this->explosion,
                'describeDamage' => $this->describeDamage,
                'identificationOACI' => $this->identificationOACI,
                'nameAerodrome' => $this->nameAerodrome,
                'distanceAerodrome' => $this->distanceAerodrome,
                'directionAerodrome' => $this->directionAerodrome,
                'elevation' => $this->elevation,
                'proximityAirport' => $this->proximityAirport,
                'approachSegment' => $this->approachSegment,
                'approachIFR' => $this->approachIFR,
                'approachVFR' => $this->approachVFR,
                'trackHeader' => $this->trackHeader,
                'longitude2' => $this->longitude2,
                'broad' => $this->broad,
                'materialHead' => $this->materialHead,
                'conditionsRunway' => $this->conditionsRunway,
                'lastTakeoff' => $this->lastTakeoff,
                'timeTakeoff' => $this->timeTakeoff,
                'destinationAirport' => $this->destinationAirport,
                'planFlight' => $this->planFlight,
                'clearanceFlight' => $this->clearanceFlight,
                'eventOccurred' => $this->eventOccurred,
                'loadAircraft' => $this->loadAircraft,
                'otherAircraft' => $this->otherAircraft,
                'litersFuel' => $this->litersFuel,
                'gallonsfuel' => $this->gallonsfuel,
                'typeFuel' => $this->typeFuel,
                'specifyFuel' => $this->specifyFuel,
                'otherService' => $this->otherService,
                // 'filereceiptFuel' => $this->filereceiptFuel->store('documentos', 'public','Recibo'),                
                'evacuationAircraft' => $this->evacuationAircraft,
                'evacuationDescription' => $this->evacuationDescription,
                // 'fileProcedures' => $this->fileProcedures->store('documentos', 'public','Procedimientos '),                
                'installationObservation' => $this->installationObservation,
                'timeObservation' => $this->timeObservation,
                'distanceAccident' => $this->distanceAccident,
                'directionAccident' => $this->directionAccident,

                'sourceInformation' => $this->sourceInformation,
                'obtainedInformation' => $this->obtainedInformation,
                'lightConditions' => $this->lightConditions,
                'skyClouds' => $this->skyClouds,
                'ceiling' => $this->ceiling,
                'lowestCloud' => $this->lowestCloud,

                'visibilityRestriction' => $this->visibilityRestriction,
                'Wind' => $this->Wind,
                'orientation' => $this->orientation,
                'intensity' => $this->intensity,
                'typeTurbulence' => $this->typeTurbulence,
                'severityTurbulence' => $this->severityTurbulence,
                'weatherConditions' => $this->weatherConditions,
                'currentTimeaccident' => $this->currentTimeaccident,
                'temperature' => $this->temperature,
                'altimeter' => $this->altimeter,
                'altitudeDensity' => $this->altitudeDensity,
                'DewPoint' => $this->DewPoint,
                'precipitationType' => $this->precipitationType,
                // 'fileForecast' => $this->fileForecast->store('documentos', 'public','Pronostico'),                                
                'nameCommander' => $this->nameCommander,
                'nacionalities_id' => $this->nacionalities_id,
                'datebirthCommander' => $this->datebirthCommander,
                'domicileCommander' => $this->domicileCommander,
                'classLicense' => $this->classLicense,
                'numberLicense' => $this->numberLicense,
                'validityLicense' => $this->validityLicense,
                'pilotAircraft' => $this->pilotAircraft,
                'pilotBumpy' => $this->pilotBumpy,
                'pilotMultiengine' => $this->pilotMultiengine,
                'pilotInstruments' => $this->pilotInstruments,
                'instructorAircraft' => $this->instructorAircraft,
                'instructorRugged' => $this->instructorRugged ,
                'instructorMultiengine' => $this->instructorMultiengine ,
                'instructorInstruments' => $this->instructorInstruments,
                'copilotAircraft' => $this->copilotAircraft,
                'copilotRugged' => $this->copilotRugged,
                'copilotMultiengine' => $this->copilotMultiengine ,
                'copilotInstruments' => $this->copilotInstruments,
                'daysAircraft90' => $this->daysAircraft90,
                'daysRugged90' => $this->daysRugged90 ,
                'daysMultiengine90' => $this->daysMultiengine90,
                'daysInstruments90' => $this->daysInstruments90,
                'daysAircraft30' => $this->daysAircraft30,
                'daysRugged30' => $this->daysRugged30,
                'daysMultiengine30' => $this->daysMultiengine30 ,
                'daysInstruments30' => $this->daysInstruments30,
                'hoursAircraft24' => $this->hoursAircraft24,
                'hoursRugged24' => $this->hoursRugged24,
                'hoursMultiengine24' => $this->hoursMultiengine24,
                'hoursInstruments24' => $this->hoursInstruments24,

                'capabilities' => $this->capabilities,
                'medicalCertificate' => $this->medicalCertificate,
                'limitationsCertificate' => $this->limitationsCertificate,
                'exceptionCertificate' => $this->exceptionCertificate,
                'observationsCertificate' => $this->observationsCertificate,
                'otherCertificate' => $this->otherCertificate,
                'occupiedSeat' => $this->occupiedSeat,
                'injury' => $this->injury,
                'performsFunctions' => $this->performsFunctions,
                'seatBelt' => $this->seatBelt,
                'theHarness' => $this->theHarness,
                'inspectionDate' => $this->inspectionDate,
                'verificationDate' => $this->verificationDate,
                // 'fileLicense' => $this->fileLicense->store('documentos', 'public','Licencia'),                  
                'nameCopilot' => $this->nameCopilot,
                'nationalitycopilot_id' => $this->nationalitycopilot_id,
                'datebirthCopilot' => $this->datebirthCopilot,
                'domicileCopilot' => $this->domicileCopilot,
                'classLicense2' => $this->classLicense2,
                'numberLicense2' => $this->numberLicense2,
                'validityLicense2' => $this->validityLicense2,
                ]
        );
    }
    public function messages()
    {
        return [
            'exactPlace.required' => 'Campo obligaotrio',
            'state_id.required' => 'Campo obligaotrio',
            'municipal_id.required' => 'Campo obligaotrio',
            'city.required' => 'Campo obligaotrio',
            'latitude.required' => 'Campo obligaotrio',
            'longitude.required' => 'Campo obligaotrio',
            'date.required' => 'Campo obligaotrio',
            'time.required' => 'Campo obligaotrio',
            'aeronauticalAuthority.required' => 'Campo obligaotrio',
            'flight_phase.required' => 'Campo obligaotrio',
            'indicate.required' => 'Campo obligaotrio',
            'collision.required' => 'Campo obligaotrio',
            'altitudeEvent.required' => 'Campo obligaotrio',
            'maker.required' => 'Campo obligaotrio',
            'modelReport.required' => 'Campo obligaotrio',
            'serialNumber.required' => 'Campo obligaotrio',
            'enrollment.required' => 'Campo obligaotrio',
            'amateur.required' => 'Campo obligaotrio',
            'maximumWeight.required' => 'Campo obligaotrio',
            'accidentWeight.required' => 'Campo obligaotrio',
            'nose.required' => 'Campo obligaotrio',
            'datum.required' => 'Campo obligaotrio',
            'noseI.required' => 'Campo obligaotrio',
            'datumI.required' => 'Campo obligaotrio',
            'aircraftCategory.required' => 'Campo obligaotrio',
            'indicateI.required' => 'Campo obligaotrio',
            'airworthiness.required' => 'Campo obligaotrio',
            'indicateII.required' => 'Campo obligaotrio',
            'numberSeats.required' => 'Campo obligaotrio',
            'flightCrew.required' => 'Campo obligaotrio',
            'cabinCrew.required' => 'Campo obligaotrio',
            'passengerSeats.required' => 'Campo obligaotrio',
            'undercarriage.required' => 'Campo obligaotrio',
            'MaintenanceProgram.required' => 'Campo obligaotrio',
            'specify.required' => 'Campo obligaotrio',
            'lastInspection.required' => 'Campo obligaotrio',
            'other.required' => 'Campo obligaotrio',
            'lastInspectionDate.required' => 'Campo obligaotrio',
            'gliderHours.required' => 'Campo obligaotrio',
            'hoursLastInsp.required' => 'Campo obligaotrio',
            'hoursTimeAccident.required' => 'Campo obligaotrio',
            'ifrTeam.required' => 'Campo obligaotrio',
            'collapseSystem.required' => 'Campo obligaotrio',
            'fireSystem.required' => 'Campo obligaotrio',
            'type.required' => 'Campo obligaotrio',
            'eltInstalled.required' => 'Campo obligaotrio',
            'eltActivated.required' => 'Campo obligaotrio',
            'eltManufacturer.required' => 'Campo obligaotrio',
            'eltModel.required' => 'Campo obligaotrio',
            'eltSerial.required' => 'Campo obligaotrio',
            'eltBattery.required' => 'Campo obligaotrio',
            'engineType.required' => 'Campo obligaotrio',
            'reciprocatingSystem.required' => 'Campo obligaotrio',
            'makerPropeller.required' => 'Campo obligaotrio',
            'modelPropeller.required' => 'Campo obligaotrio',
            'pitchPropeller.required' => 'Campo obligaotrio',
            'manufacturerEngine.required' => 'Campo obligaotrio',
            'modelEngine.required' => 'Campo obligaotrio',
            'powerEngine.required' => 'Campo obligaotrio',
            'nameOwner1.required' => 'Campo obligaotrio',
            'directionOwner1.required' => 'Campo obligaotrio',
            'nameOperator1.required' => 'Campo obligaotrio',
            'directionOperator1.required' => 'Campo obligaotrio',
            'flightPurpose.required' => 'Campo obligaotrio',
            'operation.required' => 'Campo obligaotrio',
            'loadOperation.required' => 'Campo obligaotrio',
            'passengersHow.required' => 'Campo obligaotrio',
            'concessionType.required' => 'Campo obligaotrio',
            'others.required' => 'Campo obligaotrio',
            'tuitionInvolved.required' => 'Campo obligaotrio',
            'makerInvolved.required' => 'Campo obligaotrio',
            'modelInvolved.required' => 'Campo obligaotrio',
            'damageInvolved.required' => 'Campo obligaotrio',
            'nameOwner2.required' => 'Campo obligaotrio',
            'directionOwner2.required' => 'Campo obligaotrio',
            'nameOperator2.required' => 'Campo obligaotrio',
            'directionOperator2.required' => 'Campo obligaotrio',
            'malfunction.required' => 'Campo obligaotrio',
            'descriptionFail.required' => 'Campo obligaotrio',
            'componentHours.required' => 'Campo obligaotrio',
            'componentCycles.required' => 'Campo obligaotrio',
            'componentInspection.required' => 'Campo obligaotrio',
            'a_model_id.required' => 'Campo obligaotrio',
            'presenceFire.required' => 'Campo obligaotrio',
            'explosion.required' => 'Campo obligaotrio',
            'describeDamage.required' => 'Campo obligaotrio',
            'identificationOACI.required' => 'Campo obligaotrio',
            'nameAerodrome.required' => 'Campo obligaotrio',
            'distanceAerodrome.required' => 'Campo obligaotrio',
            'directionAerodrome.required' => 'Campo obligaotrio',
            'elevation.required' => 'Campo obligaotrio',
            'proximityAirport.required' => 'Campo obligaotrio',
            'approachSegment.required' => 'Campo obligaotrio',
            'approachIFR.required' => 'Campo obligaotrio',
            'approachVFR.required' => 'Campo obligaotrio',
            'trackHeader.required' => 'Campo obligaotrio',
            'longitude2.required' => 'Campo obligaotrio',
            'broad.required' => 'Campo obligaotrio',
            'materialHead.required' => 'Campo obligaotrio',
            'conditionsRunway.required' => 'Campo obligaotrio',
            'lastTakeoff.required' => 'Campo obligaotrio',
            'timeTakeoff.required' => 'Campo obligaotrio',
            'destinationAirport.required' => 'Campo obligaotrio',
            'planFlight.required' => 'Campo obligaotrio',
            'clearanceFlight.required' => 'Campo obligaotrio',
            'eventOccurred.required' => 'Campo obligaotrio',
            'loadAircraft.required' => 'Campo obligaotrio',
            'otherAircraft.required' => 'Campo obligaotrio',
            'litersFuel.required' => 'Campo obligaotrio',
            'gallonsfuel.required' => 'Campo obligaotrio',
            'typeFuel.required' => 'Campo obligaotrio',
            'specifyFuel.required' => 'Campo obligaotrio',
            'otherService.required' => 'Campo obligaotrio',
            'evacuationAircraft.required' => 'Campo obligaotrio',
            'evacuationDescription.required' => 'Campo obligaotrio',
            'installationObservation.required' => 'Campo obligaotrio',
            'timeObservation.required' => 'Campo obligaotrio',
            'distanceAccident.required' => 'Campo obligaotrio',
            'directionAccident.required' => 'Campo obligaotrio',

        ];
    }

}
