<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('daaia001s', function (Blueprint $table) {
            $table->id();
            // $table->unsignedBigInteger('report')->nullable();
            $table->unsignedBigInteger('general_user_id')->nullable();
            $table->foreign('general_user_id')->references('id')->on('general_users')->onDelete('set null');
            $table->text('report');
            $table->string('exactPlace');
            $table->unsignedBigInteger('state_id')->nullable();
            $table->foreign('state_id')->references('id')->on('states')->onDelete('set null');
            $table->unsignedBigInteger('municipal_id')->nullable();
            $table->foreign('municipal_id')->references('id')->on('municipals')->onDelete('set null');
            $table->string('city');
            $table->string('latitude');
            $table->string('longitude');
            $table->date('date');
            $table->time('time');
            $table->text('aeronauticalAuthority');
            $table->text('flight_phase');
            $table->text('indicate')->nullable();
            $table->text('collision');
            $table->text('altitudeEvent');
            $table->text('maker');
            $table->text('modelReport');
            $table->text('serialNumber');
            $table->text('enrollment');
            $table->text('amateur');
            $table->text('maximumWeight');
            $table->text('accidentWeight');
            $table->text('nose');
            $table->text('datum');
            $table->text('noseI');
            $table->text('datumI');
            $table->text('aircraftCategory');
            $table->text('indicateI')->nullable();
            $table->text('airworthiness');
            $table->text('indicateII')->nullable();
            $table->text('numberSeats');
            $table->text('flightCrew');
            $table->text('cabinCrew');
            $table->text('passengerSeats');
            $table->text('undercarriage');
            $table->text('MaintenanceProgram');
            $table->text('specify')->nullable();
            $table->text('lastInspection');
            $table->text('other')->nullable();
            $table->date('lastInspectionDate');
            $table->text('gliderHours');
            $table->text('hoursLastInsp');
            $table->text('hoursTimeAccident');
            $table->text('ifrTeam');
            $table->text('collapseSystem');
            $table->text('fireSystem');
            $table->text('type');
            $table->text('eltInstalled');
            $table->text('eltActivated');
            $table->text('eltManufacturer');
            $table->text('eltModel');
            $table->text('eltSerial');
            $table->text('eltBattery');            
            $table->text('engineType');
            $table->text('reciprocatingSystem');
            $table->text('makerPropeller');
            $table->text('modelPropeller');
            $table->text('pitchPropeller');
            $table->text('manufacturerEngine');
            $table->text('modelEngine');
            $table->text('powerEngine');
            $table->text('engineSerie1');
            $table->text('manufacturingDate1');
            $table->text('totalTime1');
            $table->text('lastIspection1');
            $table->text('lastRrepair1');
            $table->text('engineSerie2');
            $table->text('manufacturingDate2');
            $table->text('totalTime2');
            $table->text('lastIspection2');
            $table->text('lastRrepair2');
            $table->text('engineSerie3');
            $table->text('manufacturingDate3');
            $table->text('totalTime3');
            $table->text('lastIspection3');
            $table->text('lastRrepair3');
            $table->text('engineSerie4');
            $table->text('manufacturingDate4');
            $table->text('totalTime4');
            $table->text('lastIspection4');
            $table->text('lastRrepair4');
//            $table->text('copyRevalidation');
            $table->text('nameOwner1');
            $table->text('directionOwner1');
            $table->text('nameOperator1');
            $table->text('directionOperator1');
            $table->text('flightPurpose');
            $table->text('operation');
            $table->text('loadOperation');
            $table->text('passengersHow')->nullable();
            $table->text('concessionType');
            $table->text('others')->nullable();
//            $table->text('filesPermissions');
            $table->text('tuitionInvolved');
            $table->text('makerInvolved');
            $table->text('modelInvolved');
            $table->text('damageInvolved');
            $table->text('nameOwner2');
            $table->text('directionOwner2');
            $table->text('nameOperator2');
            $table->text('directionOperator2');
            $table->text('malfunction');
            $table->text('descriptionFail');
            $table->text('componentHours');
            $table->text('componentCycles');
//          $table->text('componentInspection');
//          $table->text('filesLatestservices');            
            $table->unsignedBigInteger('a_model_id')->nullable();
            $table->foreign('a_model_id')->references('id')->on('a_models')->onDelete('set null');
            $table->text('presenceFire');
            $table->text('explosion');
            $table->text('describeDamage');
            $table->text('identificationOACI');
            $table->text('nameAerodrome');
            $table->text('distanceAerodrome');
            $table->text('directionAerodrome');
            $table->text('elevation');
            $table->text('proximityAirport');
            $table->text('approachSegment');
            $table->text('approachIFR');
            $table->text('approachVFR');
            $table->text('trackHeader');
            $table->text('longitude2');
            $table->text('broad');
            $table->text('materialHead');
            $table->text('conditionsRunway');
            $table->text('lastTakeoff');
            $table->text('timeTakeoff');
            $table->text('destinationAirport');
            $table->text('planFlight');
            $table->text('clearanceFlight');
            $table->text('eventOccurred');
            $table->text('loadAircraft');
            $table->text('otherAircraft')->nullable();
            $table->text('litersFuel');
            $table->text('gallonsfuel');
            $table->text('typeFuel');
            $table->text('specifyFuel')->nullable();
            $table->text('otherService');
//            $table->text('filereceiptFuel');
            $table->text('evacuationAircraft');
            $table->text('evacuationDescription');
//            $table->text('fileProcedures');
            $table->text('installationObservation');
            $table->text('timeObservation');
            $table->text('distanceAccident');
            $table->text('directionAccident');
            $table->text('sourceInformation');
            $table->text('obtainedInformation');
            $table->text('lightConditions');
            $table->text('skyClouds');
            $table->text('ceiling');
            $table->text('lowestCloud')->nullable();
            $table->text('visibilityRestriction');
            $table->text('Wind');
            $table->text('orientation');
            $table->text('intensity');
            $table->text('typeTurbulence');
            $table->text('severityTurbulence');
            $table->text('weatherConditions');
            $table->text('currentTimeaccident');
            $table->text('temperature');
            $table->text('altimeter');
            $table->text('altitudeDensity');
            $table->text('DewPoint');
            $table->text('precipitationType');
            // $table->text('fileForecast');
            $table->text('nameCommander');
            // $table->text('nationalityCommander');
            $table->unsignedBigInteger('nacionalities_id')->nullable();
            $table->foreign('nacionalities_id')->references('id')->on('nacionalities')->onDelete('set null');            
            $table->text('datebirthCommander');
            $table->text('domicileCommander');
            $table->text('classLicense');
            $table->text('numberLicense');
            $table->text('validityLicense');
            $table->text('pilotAircraft');
            $table->text('pilotBumpy');
            $table->text('pilotMultiengine');
            $table->text('pilotInstruments');
            $table->text('instructorAircraft');
            $table->text('instructorRugged');
            $table->text('instructorMultiengine');
            $table->text('instructorInstruments');
            $table->text('copilotAircraft');
            $table->text('copilotRugged');
            $table->text('copilotMultiengine');
            $table->text('copilotInstruments');
            $table->text('daysAircraft90');
            $table->text('daysRugged90');
            $table->text('daysMultiengine90');
            $table->text('daysInstruments90');
            $table->text('daysAircraft30');
            $table->text('daysRugged30');
            $table->text('daysMultiengine30');
            $table->text('daysInstruments30');
            $table->text('hoursAircraft24');
            $table->text('hoursRugged24');
            $table->text('hoursMultiengine24');
            $table->text('hoursInstruments24');
            $table->text('capabilities');
            $table->text('medicalCertificate');
            $table->text('limitationsCertificate');
            $table->text('exceptionCertificate');
            $table->text('observationsCertificate');
            $table->text('otherCertificate')->nullable();
            $table->text('occupiedSeat');
            $table->text('injury');
            $table->text('performsFunctions');
            $table->text('seatBelt');
            $table->text('theHarness');
            $table->text('inspectionDate');
            $table->text('verificationDate');
            // $table->text('fileLicense');                                    
            $table->text('nameCopilot');
            $table->unsignedBigInteger('nationalitycopilot_id')->nullable();
            $table->foreign('nationalitycopilot_id')->references('id')->on('nacionalities')->onDelete('set null');
            // $table->text('nationalityCopilot');
            $table->text('datebirthCopilot');
            $table->text('domicileCopilot');
            $table->text('classLicense2');
            $table->text('numberLicense2');
            $table->text('validityLicense2');

            $table->text('pilotAircraft2');
            $table->text('pilotBumpy2');
            $table->text('pilotMultiengine2');
            $table->text('pilotInstruments2');
            $table->text('instructorAircraft2');
            $table->text('instructorRugged2');
            $table->text('instructorMultiengine2');
            $table->text('instructorInstruments2');
            $table->text('copilotAircraft2');
            $table->text('copilotRugged2');
            $table->text('copilotMultiengine2');
            $table->text('copilotInstruments2');
            $table->text('daysAircraft902');
            $table->text('daysRugged902');
            $table->text('daysMultiengine902');
            $table->text('daysInstruments902');
            $table->text('daysAircraft302');
            $table->text('daysRugged302');
            $table->text('daysMultiengine302');
            $table->text('daysInstruments302');
            $table->text('hoursAircraft242');
            $table->text('hoursRugged242');
            $table->text('hoursMultiengine242');
            $table->text('hoursInstruments242');

            $table->text('capabilities2');
            $table->text('medicalCertificate2');
            $table->text('limitationsCertificate2');
            $table->text('exceptionCertificate2');
            $table->text('observationsCertificate2');
            $table->text('otherCertificate2')->nullable();
            $table->text('occupiedSeat2');
            $table->text('injury2');
            $table->text('performsFunctions2');
            $table->text('seatBelt2');
            $table->text('theHarness2');
            $table->text('inspectionDate2');
            $table->text('verificationDate2');
            // $table->text('fileBinnacle');  
            $table->text('nameOthers');    
            $table->unsignedBigInteger('nationalityother_id')->nullable();
            $table->foreign('nationalityother_id')->references('id')->on('nacionalities')->onDelete('set null');
            $table->text('datebirthOthers');
            $table->text('domicileOthers');
            $table->text('classLicense3');
            $table->text('numberLicense3');
            $table->text('validityLicense3');
            $table->text('pilotAircraft3');
            $table->text('pilotBumpy3');
            $table->text('pilotMultiengine3');
            $table->text('pilotInstruments3');
            $table->text('instructorAircraft3');
            $table->text('instructorRugged3');
            $table->text('instructorMultiengine3');
            $table->text('instructorInstruments3');
            $table->text('copilotAircraft3');
            $table->text('copilotRugged3');
            $table->text('copilotMultiengine3');
            $table->text('copilotInstruments3');
            $table->text('daysAircraft903');
            $table->text('daysRugged903');
            $table->text('daysMultiengine903');
            $table->text('daysInstruments903');
            $table->text('daysAircraft303');
            $table->text('daysRugged303');
            $table->text('daysMultiengine303');
            $table->text('daysInstruments303');
            $table->text('hoursAircraft243');
            $table->text('hoursRugged243');
            $table->text('hoursMultiengine243');
            $table->text('hoursInstruments243');
            $table->text('capabilities3');
            $table->text('medicalCertificate3');
            $table->text('limitationsCertificate3');
            $table->text('exceptionCertificate3');
            $table->text('observationsCertificate3');
            $table->text('otherCertificate3')->nullable();
            $table->text('occupiedSeat3');
            $table->text('injury3');
            $table->text('performsFunctions3');
            $table->text('seatBelt3');
            $table->text('theHarness3');
            $table->text('inspectionDate3');
            $table->text('verificationDate3');
            // $table->text('fileCertificate');                          
            $table->text('historyDescription');
            // $table->text('filePassengers');
            $table->text('safetyRecommendation');
            // $table->text('fileSusceptible');
            $table->text('additionalInformation');
            


            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('daaia001s');
    }
};
